/**
 * Styles only the tasks table and cards need.
 * Generic page/row/chip recipes live in shared/styles/recipes.ts;
 * this module keeps task-specific cells, badges and action buttons.
 * Called by TasksPage, TaskRow and TaskCard.
 */
import * as T from '../../shared/styles/tokens';

export const styles = {
  filterBtnInner: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.3rem',
  } as React.CSSProperties,
  alertDot: {
    display: 'inline-block',
    width: 7,
    height: 7,
    borderRadius: '50%',
    background: T.colors.danger,
    flexShrink: 0,
  } as React.CSSProperties,
  colStatus:  { width: '5rem', flexShrink: 0 } as React.CSSProperties,
  colId:      { width: '6rem', flexShrink: 0 } as React.CSSProperties,
  colTitle:   { flex: 1, minWidth: 0 } as React.CSSProperties,
  colCoder:   { width: '9rem', flexShrink: 0 } as React.CSSProperties,
  colContext: { width: '5rem', flexShrink: 0 } as React.CSSProperties,
  colRuns:    { width: '4rem', flexShrink: 0 } as React.CSSProperties,
  colTs:      { width: '8.5rem', flexShrink: 0 } as React.CSSProperties,
  colCwd:     { width: '7rem', flexShrink: 0 } as React.CSSProperties,
  colAction:  { width: '10rem', flexShrink: 0 } as React.CSSProperties,
  titleCol: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.1rem',
    overflow: 'hidden',
  } as React.CSSProperties,
  titleText: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  descText: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: '0.75rem',
    color: T.colors.textMuted,
  } as React.CSSProperties,
  blockedReason: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: '0.75rem',
    color: '#f59e0b',
  } as React.CSSProperties,
  staleLeaseBadge: {
    display: 'inline-block',
    padding: '0.05rem 0.4rem',
    borderRadius: 4,
    border: '1px solid #f59e0b',
    color: '#f59e0b',
    fontSize: '0.7rem',
    fontWeight: 600,
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  ignoredBadge: {
    display: 'inline-block',
    padding: '0.05rem 0.4rem',
    borderRadius: 4,
    border: '1px solid #94a3b8',
    color: '#94a3b8',
    fontSize: '0.7rem',
    fontWeight: 600,
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  coderCell: {
    width: '9rem',
    flexShrink: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: '0.8125rem',
  } as React.CSSProperties,
  contextCell: {
    width: '5rem',
    flexShrink: 0,
    color: T.colors.textSecondary,
    fontSize: '0.8125rem',
  } as React.CSSProperties,
  runsCell: {
    width: '4rem',
    flexShrink: 0,
    color: T.colors.textSecondary,
    fontSize: '0.8125rem',
  } as React.CSSProperties,
  runsChip: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0.1rem 0.4rem',
    borderRadius: 4,
    background: '#3f3f46',
    color: T.colors.textPrimary,
    fontSize: '0.75rem',
    fontWeight: 600,
  } as React.CSSProperties,
  tsCell: {
    width: '8.5rem',
    flexShrink: 0,
    color: T.colors.textSecondary,
    fontSize: '0.8125rem',
    fontFamily: 'monospace',
  } as React.CSSProperties,
  cwdCell: {
    width: '7rem',
    flexShrink: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    color: T.colors.textDim,
    fontSize: '0.8125rem',
  } as React.CSSProperties,
  actionCell: {
    width: '10rem',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
  } as React.CSSProperties,
  killBtn: {
    ...T.btnDanger,
    padding: '0.2rem 0.625rem',
    fontSize: '0.8125rem',
  } as React.CSSProperties,
  unblockBtn: {
    padding: '0.2rem 0.625rem',
    background: 'transparent',
    border: '1px solid #f59e0b',
    borderRadius: 4,
    color: '#f59e0b',
    cursor: 'pointer',
    fontSize: '0.8125rem',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 600,
  } as React.CSSProperties,
  stoppingLabel: {
    fontSize: '0.8125rem',
    color: '#fb923c',
    fontStyle: 'italic',
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  confirm: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
  } as React.CSSProperties,
  confirmLabel: {
    fontSize: '0.8125rem',
    color: T.colors.textSecondary,
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  yesBtn: {
    padding: '0.2rem 0.5rem',
    background: T.colors.danger,
    border: `1px solid ${T.colors.danger}`,
    borderRadius: 4,
    color: '#fff',
    cursor: 'pointer',
    fontSize: '0.8125rem',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 600,
  } as React.CSSProperties,
  cancelBtn: {
    ...T.btnGhost,
    padding: '0.2rem 0.5rem',
    fontSize: '0.8125rem',
  } as React.CSSProperties,
};

export const cardStyles = {
  card: {
    padding: '0.625rem 0.875rem',
    borderBottom: `1px solid ${T.colors.borderSubtle}`,
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.3rem',
    fontSize: '0.875rem',
    color: '#d4d4d8',
  } as React.CSSProperties,
  cardHead: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  } as React.CSSProperties,
  chipInCard: {
    flexShrink: 0,
    width: 'auto',
  } as React.CSSProperties,
  cardId: {
    fontFamily: 'monospace',
    color: '#60a5fa',
    fontSize: '0.8125rem',
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  cardActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
    flexShrink: 0,
  } as React.CSSProperties,
  cardTitle: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  cardDesc: {
    fontSize: '0.75rem',
    color: T.colors.textMuted,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  cardMeta: {
    display: 'flex',
    gap: '0.625rem',
    flexWrap: 'wrap' as const,
  } as React.CSSProperties,
  cardMetaText: {
    fontSize: '0.75rem',
    color: T.colors.textSecondary,
  } as React.CSSProperties,
};
