/**
 * Styles only the tasks table and cards need.
 * Generic page/row/chip recipes live in shared/styles/recipes.ts;
 * this module keeps task-specific cells, badges and action buttons.
 * Called by WorkersPage, WorkerRow and WorkerCard.
 */
import * as T from '../../shared/styles/tokens';

export const rowStyles = {
  titleCol: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.1rem',
    overflow: 'hidden',
  } as React.CSSProperties,
  titleText: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  descText: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: '0.75rem',
    color: T.colors.textMuted,
  } as React.CSSProperties,
  blockedReason: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: '0.75rem',
    color: T.colors.amber,
  } as React.CSSProperties,
  staleLeaseBadge: {
    display: 'inline-block',
    padding: '0.05rem 0.4rem',
    borderRadius: '0.25rem',
    border: `1px solid ${T.colors.amber}`,
    color: T.colors.amber,
    fontSize: '0.7rem',
    fontWeight: 600,
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  ignoredBadge: {
    display: 'inline-block',
    padding: '0.05rem 0.4rem',
    borderRadius: '0.25rem',
    border: `1px solid ${T.colors.slateLight}`,
    color: T.colors.slateLight,
    fontSize: '0.7rem',
    fontWeight: 600,
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  queuedBadge: {
    display: 'inline-block',
    padding: '0.05rem 0.4rem',
    borderRadius: '0.25rem',
    color: T.colors.textMuted,
    fontSize: '0.7rem',
    fontStyle: 'italic',
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  coderCell: {
    display: 'block',
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    fontSize: '0.8125rem',
  } as React.CSSProperties,
  coderName: {
    display: 'block',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  coderModel: {
    display: 'block',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    fontSize: '0.75rem',
    color: T.colors.textMuted,
  } as React.CSSProperties,
  contextCell: {
    display: 'block',
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    color: T.colors.textSecondary,
    fontSize: '0.8125rem',
  } as React.CSSProperties,
  runsCell: {
    display: 'block',
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    color: T.colors.textSecondary,
    fontSize: '0.8125rem',
  } as React.CSSProperties,
  runsChip: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0.1rem 0.4rem',
    borderRadius: '0.25rem',
    background: T.colors.border,
    color: T.colors.textPrimary,
    fontSize: '0.75rem',
    fontWeight: 600,
  } as React.CSSProperties,
  tsCell: {
    display: 'block',
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    color: T.colors.textSecondary,
    fontSize: '0.8125rem',
    fontFamily: 'monospace',
  } as React.CSSProperties,
  cwdCell: {
    display: 'block',
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    color: T.colors.textDim,
    fontSize: '0.8125rem',
  } as React.CSSProperties,
  actionCell: {
    width: '10rem',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
  } as React.CSSProperties,
  killBtn: {
    ...T.btnDanger,
    padding: '0.2rem 0.625rem',
    fontSize: '0.8125rem',
  } as React.CSSProperties,
  unblockBtn: {
    padding: '0.2rem 0.625rem',
    background: 'transparent',
    border: `1px solid ${T.colors.amber}`,
    borderRadius: '0.25rem',
    color: T.colors.amber,
    cursor: 'pointer',
    fontSize: '0.8125rem',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 600,
  } as React.CSSProperties,
  retryBtn: {
    padding: '0.2rem 0.625rem',
    background: 'transparent',
    border: `1px solid ${T.colors.amber}`,
    borderRadius: '0.25rem',
    color: T.colors.amber,
    cursor: 'pointer',
    fontSize: '0.8125rem',
    fontFamily: 'system-ui, sans-serif',
    fontWeight: 600,
  } as React.CSSProperties,
  closeBtn: {
    ...T.btnGhost,
    padding: '0.2rem 0.625rem',
    fontSize: '0.8125rem',
  } as React.CSSProperties,
  stoppingLabel: {
    fontSize: '0.8125rem',
    color: T.colors.orange,
    fontStyle: 'italic',
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
};

export const cardStyles = {
  card: {
    padding: '0.625rem 0.875rem',
    borderBottom: `1px solid ${T.colors.borderSubtle}`,
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.3rem',
    fontSize: '0.875rem',
    color: T.colors.textBody,
  } as React.CSSProperties,
  cardHead: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  } as React.CSSProperties,
  chipInCard: {
    flexShrink: 0,
    width: 'auto',
  } as React.CSSProperties,
  cardId: {
    fontFamily: 'monospace',
    color: T.colors.link,
    fontSize: '0.8125rem',
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  cardActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.375rem',
    flexShrink: 0,
  } as React.CSSProperties,
  cardTitle: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  cardDesc: {
    fontSize: '0.75rem',
    color: T.colors.textMuted,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  } as React.CSSProperties,
  cardMeta: {
    display: 'flex',
    gap: '0.625rem',
    flexWrap: 'wrap' as const,
  } as React.CSSProperties,
  cardMetaText: {
    fontSize: '0.75rem',
    color: T.colors.textSecondary,
  } as React.CSSProperties,
};
