/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description List task summaries, active first then recently-closed (FR-07).
         */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /**
         * Create Task
         * @description Create a task via the queue; 201 with the new id.
         */
        post: operations["create_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Coders
         * @description Coders the create-task form may offer.
         */
        get: operations["coders_api_coders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description Prompt templates stored under the fleet home.
         */
        get: operations["list_templates_api_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task
         * @description One task summary, overlaid with beads status/priority/depends_on.
         */
        get: operations["get_task_api_tasks__task_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Task
         * @description Delete a task via the queue.
         */
        delete: operations["delete_task_api_tasks__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Task Attempts
         * @description Attempt timeline for one task, derived from attempts.jsonl.
         */
        get: operations["list_task_attempts_api_tasks__task_id__attempts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Children
         * @description Children panel for epics: child id/status/RESULT plus CHILDREN.md.
         */
        get: operations["get_task_children_api_tasks__task_id__children_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/attempts/{attempt_no}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Attempt Summary
         * @description Derived attempt summary, rendered on demand (never stored).
         */
        get: operations["get_attempt_summary_api_tasks__task_id__attempts__attempt_no__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/attempts/{attempt_no}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Attempt State
         * @description STATE.md snapshot taken at reap for one attempt.
         */
        get: operations["get_attempt_state_api_tasks__task_id__attempts__attempt_no__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/attempts/{attempt_no}/prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Attempt Prompt
         * @description Recorded prompt.md for one attempt.
         */
        get: operations["get_attempt_prompt_api_tasks__task_id__attempts__attempt_no__prompt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/attempts/{attempt_no}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Attempt Log
         * @description Raw log.jsonl for one attempt.
         */
        get: operations["get_attempt_log_api_tasks__task_id__attempts__attempt_no__log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kill Task
         * @description Signal a running task (.kill) or close a queued one via the queue.
         */
        post: operations["kill_task_api_tasks__task_id__kill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/requeue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Requeue Task
         * @description Release a task back to the queue.
         */
        post: operations["requeue_task_api_tasks__task_id__requeue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unblock Task
         * @description Release a blocked task, clear retry state, journal the note.
         */
        post: operations["unblock_task_api_tasks__task_id__unblock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/unignore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unignore Task
         * @description Clear a task's triage ignore.
         */
        post: operations["unignore_task_api_tasks__task_id__unignore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Task
         * @description Close a task via the queue.
         */
        post: operations["close_task_api_tasks__task_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/remove-assignee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove Assignee
         * @description Clear the beads assignee and the task.json coder mirror.
         */
        post: operations["remove_assignee_api_tasks__task_id__remove_assignee_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/artifacts/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact State
         * @description STATE.md, or the legacy view for old task dirs without one.
         */
        get: operations["get_artifact_state_api_tasks__task_id__artifacts_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/artifacts/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact Result
         * @description Live RESULT.json, else the latest attempt snapshot, else legacy.
         */
        get: operations["get_artifact_result_api_tasks__task_id__artifacts_result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/artifacts/outputs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact Outputs
         * @description Deliverables under tasks/<id>/outputs/.
         */
        get: operations["get_artifact_outputs_api_tasks__task_id__artifacts_outputs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/artifacts/research": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact Research
         * @description Job worker's RESEARCH.md (see workers/job.py).
         */
        get: operations["get_artifact_research_api_tasks__task_id__artifacts_research_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/artifacts/design": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Artifact Design
         * @description Job worker's DESIGN.md (see workers/job.py).
         */
        get: operations["get_artifact_design_api_tasks__task_id__artifacts_design_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Diff
         * @description git diff of the task's cwd (empty when not a git repo).
         */
        get: operations["get_task_diff_api_tasks__task_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Logs
         * @description Parsed log.jsonl lines, optionally filtered by level (FR-17).
         */
        get: operations["get_task_logs_api_tasks__task_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/stderr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Stderr
         * @description Raw stderr content, empty when absent (FR-18).
         */
        get: operations["get_task_stderr_api_tasks__task_id__stderr_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Files
         * @description Per-file read/edit/write counts from the event scan (FR-20).
         */
        get: operations["get_task_files_api_tasks__task_id__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Events
         * @description Whole-task event history across attempts, paged (tail by default).
         */
        get: operations["get_task_events_api_tasks__task_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Beads
         * @description List every bead in the beads DB.
         */
        get: operations["list_beads_api_beads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beads/{bead_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Bead
         * @description One bead with description, notes, dependencies, comments.
         */
        get: operations["get_bead_api_beads__bead_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beads/{bead_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Status
         * @description Set a bead status; `closed` goes through `bd close` like queue.close.
         */
        post: operations["set_status_api_beads__bead_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beads/{bead_id}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unblock Bead
         * @description Reopen a bead (`bd update --status open`).
         */
        post: operations["unblock_bead_api_beads__bead_id__unblock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beads/{bead_id}/remove-assignee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove Bead Assignee
         * @description Clear the assignee; the portal targets beads, so a missing task dir is ok.
         */
        post: operations["remove_bead_assignee_api_beads__bead_id__remove_assignee_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supervisor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Supervisor Status
         * @description Supervisor liveness, slot counts, pause flag, code staleness (FR-42).
         */
        get: operations["get_supervisor_status_api_supervisor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supervisor/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Supervisor
         * @description Pause claiming (running workers finish).
         */
        post: operations["pause_supervisor_api_supervisor_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supervisor/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Supervisor
         * @description Clear the pause flag.
         */
        post: operations["resume_supervisor_api_supervisor_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/supervisor/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart Supervisor
         * @description Restart the supervisor daemon; returns the new pid facts.
         */
        post: operations["restart_supervisor_api_supervisor_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness with fleet home, serve fingerprint and code staleness.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Full RuntimeConfig as JSON (FR-43).
         */
        get: operations["get_config_api_config_get"];
        /**
         * Put Config
         * @description Update runtime.toml atomically; rejects unknown coders/values.
         */
        put: operations["put_config_api_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Summary
         * @description Aggregated analytics summary for the trailing *days*.
         */
        get: operations["get_summary_api_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Full-text search over task titles, descriptions and STATE.md.
         */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Questions
         * @description Pending ask_human questions for the chat tab.
         */
        get: operations["list_questions_api_chat_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/questions/{qid}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer Question
         * @description Record the operator's answer to one question.
         */
        post: operations["answer_question_api_chat_questions__qid__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyticsByModelRow
         * @description One per-(coder, model) breakdown row.
         */
        AnalyticsByModelRow: {
            /** Coder */
            coder: string;
            /** Model */
            model: string;
            /** Total */
            total: number;
            /** Success Rate */
            success_rate: number;
            /** Median Run Sec */
            median_run_sec: number;
            /** Mean Peak Context Tokens */
            mean_peak_context_tokens: number;
            /** Output Tokens */
            output_tokens: number | null;
            /** Avg Segments */
            avg_segments: number | null;
            /** Errors */
            errors: number;
            /** Rate Limited */
            rate_limited: number;
        };
        /**
         * AnalyticsByProjectRow
         * @description One per-cwd breakdown row.
         */
        AnalyticsByProjectRow: {
            /** Cwd */
            cwd?: string | null;
            /** Total */
            total: number;
            /** Success Rate */
            success_rate: number;
            /** Median Run Sec */
            median_run_sec: number;
            /** Output Tokens */
            output_tokens: number | null;
        };
        /**
         * AnalyticsContextHistogram
         * @description Peak-context bucket counts keyed by label.
         */
        AnalyticsContextHistogram: {
            /** Buckets */
            buckets: {
                [key: string]: number;
            };
        };
        /**
         * AnalyticsErrorRecent
         * @description One task needing attention.
         */
        AnalyticsErrorRecent: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Coder */
            coder: string | null;
            /** Model */
            model: string | null;
            /** Outcome */
            outcome: string | null;
            /** Ended At */
            ended_at: string | null;
        };
        /**
         * AnalyticsKpis
         * @description Headline KPIs for the analytics summary.
         */
        AnalyticsKpis: {
            /** Completed */
            completed: number;
            /** Success Rate */
            success_rate: number;
            /** Active Now */
            active_now: number;
            /** Queued */
            queued: number;
            /** Median Run Sec */
            median_run_sec: number | null;
            /** P90 Run Sec */
            p90_run_sec: number | null;
            /** Median Queue Wait Sec */
            median_queue_wait_sec: number | null;
            /** Total Output Tokens */
            total_output_tokens: number | null;
            /** Total Input Tokens */
            total_input_tokens?: number | null;
            /** Total Cache Read Tokens */
            total_cache_read_tokens?: number | null;
            /** Total Cache Creation Tokens */
            total_cache_creation_tokens?: number | null;
            /** Total Steps */
            total_steps: number | null;
            /** Avg Segments */
            avg_segments: number | null;
            /** Error Events */
            error_events: number | null;
            /** Noclose Count */
            noclose_count: number | null;
            /** Rate Limited Tasks */
            rate_limited_tasks: number | null;
        };
        /**
         * AnalyticsRateLimit
         * @description One raw rate-limit event.
         */
        AnalyticsRateLimit: {
            /** Task Id */
            task_id: string;
            /** Ts */
            ts: string;
        };
        /**
         * AnalyticsSummary
         * @description Aggregated payload for GET /api/analytics/summary.
         */
        AnalyticsSummary: {
            /** Window Days */
            window_days: number;
            kpis: components["schemas"]["AnalyticsKpis"];
            throughput: components["schemas"]["AnalyticsThroughput"];
            token_throughput: components["schemas"]["AnalyticsTokenThroughput"];
            /** By Model */
            by_model: components["schemas"]["AnalyticsByModelRow"][];
            /** By Project */
            by_project: components["schemas"]["AnalyticsByProjectRow"][];
            tools: components["schemas"]["AnalyticsTools"];
            context_histogram: components["schemas"]["AnalyticsContextHistogram"];
            /** Heatmap */
            heatmap: number[][];
            /** Errors Recent */
            errors_recent: components["schemas"]["AnalyticsErrorRecent"][];
            /** Rate Limits */
            rate_limits: components["schemas"]["AnalyticsRateLimit"][];
        };
        /**
         * AnalyticsThroughput
         * @description Completion throughput with its bucket size.
         */
        AnalyticsThroughput: {
            /** Bucket Size */
            bucket_size: string;
            /** Buckets */
            buckets: components["schemas"]["AnalyticsThroughputBucket"][];
        };
        /**
         * AnalyticsThroughputBucket
         * @description Success/failed/blocked counts for one time bucket.
         */
        AnalyticsThroughputBucket: {
            /** Bucket */
            bucket: string;
            /** Success */
            success: number;
            /** Failed */
            failed: number;
            /** Blocked */
            blocked: number;
        };
        /**
         * AnalyticsTokenBucket
         * @description Output/input/cache tokens for one time bucket.
         */
        AnalyticsTokenBucket: {
            /** Bucket */
            bucket: string;
            /** Output Tokens */
            output_tokens: number;
            /** Input Tokens */
            input_tokens: number;
            /** Cache Tokens */
            cache_tokens: number;
        };
        /**
         * AnalyticsTokenThroughput
         * @description Token throughput with its bucket size.
         */
        AnalyticsTokenThroughput: {
            /** Bucket Size */
            bucket_size: string;
            /** Buckets */
            buckets: components["schemas"]["AnalyticsTokenBucket"][];
        };
        /**
         * AnalyticsToolRow
         * @description One tool-usage row.
         */
        AnalyticsToolRow: {
            /** Name */
            name: string;
            /** Count */
            count: number;
        };
        /**
         * AnalyticsTools
         * @description Tool usage totals with top rows.
         */
        AnalyticsTools: {
            /** Total */
            total: number;
            /** Rows */
            rows: components["schemas"]["AnalyticsToolRow"][];
        };
        /**
         * AnswerResponse
         * @description Outcome envelope for POST /api/chat/questions/{id}/answer.
         */
        AnswerResponse: {
            /** Ok */
            ok: boolean;
            /** Status */
            status: string;
        };
        /**
         * ArtifactResponse
         * @description File content envelope for the artifact routes.
         */
        ArtifactResponse: {
            /** Content */
            content: string;
            /** Mtime */
            mtime: number;
            /** Path */
            path: string;
        };
        /**
         * Bead
         * @description One beads-DB row for the BD portal list.
         */
        Bead: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Priority */
            priority: number | null;
            /** Issue Type */
            issue_type: string | null;
            /** Assignee */
            assignee: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
            /** Closed At */
            closed_at: string | null;
            /** Dependency Count */
            dependency_count: number | null;
            /** Dependent Count */
            dependent_count: number | null;
            /** Comment Count */
            comment_count: number | null;
        };
        /**
         * BeadComment
         * @description One comment on a bead detail.
         */
        BeadComment: {
            /** Id */
            id: string | number | null;
            /** Author */
            author: string | null;
            /** Text */
            text: string | null;
            /** Created At */
            created_at: string | null;
        };
        /**
         * BeadDependency
         * @description One dependency edge on a bead detail.
         */
        BeadDependency: {
            /** Id */
            id: string | null;
            /** Title */
            title: string | null;
            /** Status */
            status: string | null;
            /** Dependency Type */
            dependency_type: string | null;
        };
        /**
         * BeadDetail
         * @description One bead with description, notes, dependencies and comments.
         */
        BeadDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Priority */
            priority: number | null;
            /** Issue Type */
            issue_type: string | null;
            /** Assignee */
            assignee: string | null;
            /** Description */
            description: string | null;
            /** Notes */
            notes: string | null;
            /** Created At */
            created_at: string | null;
            /** Updated At */
            updated_at: string | null;
            /** Closed At */
            closed_at: string | null;
            /** Close Reason */
            close_reason: string | null;
            /** Dependencies */
            dependencies: components["schemas"]["BeadDependency"][];
            /** Comments */
            comments: components["schemas"]["BeadComment"][];
        };
        /**
         * BeadListResponse
         * @description Envelope for GET /api/beads.
         */
        BeadListResponse: {
            /** Beads */
            beads: components["schemas"]["Bead"][];
        };
        /**
         * CoderInfo
         * @description One coder entry for the create-task form.
         */
        CoderInfo: {
            /** Name */
            name: string;
            /** Context Limit */
            context_limit: number;
            /** Default Model */
            default_model: string;
        };
        /**
         * CoderListResponse
         * @description Envelope for GET /api/coders.
         */
        CoderListResponse: {
            /** Coders */
            coders: components["schemas"]["CoderInfo"][];
        };
        /**
         * ConfigView
         * @description Full RuntimeConfig as JSON (mirrors core.config.RuntimeConfig).
         */
        ConfigView: {
            /** Max Concurrent */
            max_concurrent: number;
            /** Model */
            model: string;
            /** Coder */
            coder: string;
            /** Telegram Chat Id */
            telegram_chat_id: string;
            /** Telegram Allowed Ids */
            telegram_allowed_ids: string;
            /** Telegram Default Cwd */
            telegram_default_cwd: string;
            /** Opencode Ollama Url */
            opencode_ollama_url: string;
            /** Max Concurrent Overrides */
            max_concurrent_overrides: string;
            /** Context Windows */
            context_windows: string;
            /** Opencode Default Model */
            opencode_default_model: string;
            /** Opencode Bedrock Region */
            opencode_bedrock_region: string;
            /** Opencode Bedrock Profile */
            opencode_bedrock_profile: string;
            /** Stall Warning Minutes */
            stall_warning_minutes: number;
            /** Stall Action */
            stall_action: string;
            /** Stall Block After */
            stall_block_after: number;
            /** Max Attempt Minutes */
            max_attempt_minutes: number;
            /** Continue Pack Max Bytes */
            continue_pack_max_bytes: number;
            /** State Max Bytes */
            state_max_bytes: number;
            /** Compaction Enabled */
            compaction_enabled: boolean;
            /** Compaction Coder */
            compaction_coder: string;
            /** Compaction Model */
            compaction_model: string;
            /** Context Checkpoint Pct */
            context_checkpoint_pct: number;
            /** Context Kill Pct */
            context_kill_pct: number;
            /** Isolation */
            isolation: string;
            /** Isolation Exclude */
            isolation_exclude: string;
            /** Post Merge Command */
            post_merge_command: string;
            /** Triage Interval Minutes */
            triage_interval_minutes: number;
            /** Gc Retention Days */
            gc_retention_days: number;
            /** Gc Archive Days */
            gc_archive_days: number;
            /** Observer Max Followups */
            observer_max_followups: number;
            /** Observer Max Rounds */
            observer_max_rounds: number;
            /** Job Gate */
            job_gate: boolean;
            /** Job Child Coder */
            job_child_coder: string;
            /** Job Child Model */
            job_child_model: string;
            /** Job Max Children */
            job_max_children: number;
            /** Job Max Phase Attempts */
            job_max_phase_attempts: number;
        };
        /**
         * ContentResponse
         * @description Single-text envelope (attempt summary/prompt/log/state, stderr).
         */
        ContentResponse: {
            /** Content */
            content: string;
        };
        /**
         * CreateTaskResponse
         * @description New task id for POST /api/tasks.
         */
        CreateTaskResponse: {
            /** Id */
            id: string;
        };
        /**
         * DiffResponse
         * @description git diff envelope for GET /api/tasks/{id}/diff.
         */
        DiffResponse: {
            /** Diff */
            diff: string;
        };
        /**
         * FileListResponse
         * @description Envelope for GET /api/tasks/{id}/files.
         */
        FileListResponse: {
            /** Files */
            files: components["schemas"]["FileOp"][];
        };
        /**
         * FileOp
         * @description Per-file read/edit/write counts from the event scan.
         */
        FileOp: {
            /** Path */
            path: string;
            /** Read */
            read: number;
            /** Edit */
            edit: number;
            /** Write */
            write: number;
        };
        /**
         * FollowupItem
         * @description One observer-declared follow-up bead inside a partial result.
         */
        FollowupItem: {
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Body
             * @default
             */
            body: string;
            /** Cwd */
            cwd?: string | null;
            /** Depends On */
            depends_on?: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness payload for GET /healthz.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Fleet Home */
            fleet_home: string;
            /** Version Fingerprint */
            version_fingerprint?: string | null;
            /** Current Fingerprint */
            current_fingerprint?: string | null;
            /** Stale */
            stale?: boolean | null;
        };
        /**
         * JobArtifacts
         * @description Presence flags for the job worker's RESEARCH/DESIGN/tasks/APPROVED.
         */
        JobArtifacts: {
            /** Research */
            research: boolean;
            /** Design */
            design: boolean;
            /** Tasks */
            tasks: boolean;
            /** Approved */
            approved: boolean;
        };
        /**
         * KillResponse
         * @description Outcome envelope for POST /api/tasks/{id}/kill.
         */
        KillResponse: {
            /** Ok */
            ok: boolean;
            /** Result */
            result: string;
        };
        /**
         * LogLine
         * @description One parsed log.jsonl line.
         */
        LogLine: {
            /** Ts */
            ts: string;
            /** Level */
            level: string;
            /** Message */
            message: string;
            /** Extra */
            extra: {
                [key: string]: unknown;
            };
        };
        /**
         * LogListResponse
         * @description Envelope for GET /api/tasks/{id}/logs.
         */
        LogListResponse: {
            /** Lines */
            lines: components["schemas"]["LogLine"][];
        };
        /**
         * OkResponse
         * @description Generic mutation acknowledgement ({"ok": true}).
         */
        OkResponse: {
            /** Ok */
            ok: boolean;
        };
        /**
         * OutputsResponse
         * @description Deliverable names for GET /api/tasks/{id}/artifacts/outputs.
         */
        OutputsResponse: {
            /** Files */
            files: string[];
        };
        /**
         * PauseResponse
         * @description Envelope for POST /api/supervisor/pause and /resume.
         */
        PauseResponse: {
            /** Paused */
            paused: boolean;
        };
        /**
         * Question
         * @description One ask_human question row for the chat tab.
         */
        Question: {
            /** Id */
            id: string;
            /** Agent Id */
            agent_id: string | null;
            /** Session Id */
            session_id: string | null;
            /** Prompt */
            prompt: string;
            /** Options */
            options: string[] | null;
            /** Multi Select */
            multi_select: boolean;
            /** Priority */
            priority: number;
            /** Status */
            status: string;
            /** Answer */
            answer: unknown | null;
            /** Note */
            note: string | null;
            /** Default Answer */
            default_answer: string | string[] | null;
            /** Timeout S */
            timeout_s: number | null;
            /** Answered By */
            answered_by: string | null;
            /** Created At */
            created_at: number;
            /** Answered At */
            answered_at: number | null;
            /** Task Id */
            task_id: string | null;
            /** Context */
            context: string | null;
        };
        /**
         * QuestionListResponse
         * @description Envelope for GET /api/chat/questions.
         */
        QuestionListResponse: {
            /** Now */
            now: number;
            /** Pending */
            pending: components["schemas"]["Question"][];
        };
        /**
         * RestartResponse
         * @description New pid facts for POST /api/supervisor/restart.
         */
        RestartResponse: {
            /** Pid */
            pid: number | null;
            /** Alive */
            alive: boolean;
            /** Started At */
            started_at: string | null;
        };
        /**
         * RunStep
         * @description One entry of the current attempt's run.json steps.
         */
        RunStep: {
            /** Name */
            name: string;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "fail" | "outcome";
            /** Reason */
            reason: string;
        };
        /**
         * SearchHit
         * @description One match: which task, which field, and a snippet around the hit.
         */
        SearchHit: {
            /** Task Id */
            task_id: string;
            /** Task Title */
            task_title: string;
            /** Source */
            source: string;
            /** Match Context */
            match_context: string;
        };
        /**
         * SearchResponse
         * @description Envelope for GET /api/search.
         */
        SearchResponse: {
            /** Results */
            results: components["schemas"]["SearchHit"][];
        };
        /**
         * StreamEvent
         * @description One shaped event row for GET /api/tasks/{id}/events.
         */
        StreamEvent: {
            /** I */
            i: number;
            /** Ts */
            ts: string;
            /** Kind */
            kind: string;
            /** Session Id */
            session_id: string | null;
            /** Tool Name */
            tool_name: string | null;
            /** Usage */
            usage: {
                [key: string]: number;
            } | null;
            /** Summary */
            summary: string;
            /** Raw */
            raw: {
                [key: string]: unknown;
            };
        };
        /**
         * SupervisorResponse
         * @description Supervisor liveness, slots, pause flag and code staleness.
         */
        SupervisorResponse: {
            /** Pid */
            pid: number | null;
            /** Started At */
            started_at: string | null;
            /** Running */
            running: boolean;
            /** Max Concurrent */
            max_concurrent: number;
            /** Active Count */
            active_count: number;
            /** Free Slots */
            free_slots: number;
            /** Paused */
            paused: boolean;
            /** Version Fingerprint */
            version_fingerprint?: string | null;
            /** Stale */
            stale?: boolean | null;
        };
        /**
         * TaskAttempt
         * @description One row of the attempts timeline.
         */
        TaskAttempt: {
            /** N */
            n: number;
            /** Kind */
            kind: string;
            /** Mode */
            mode: string | null;
            /** Coder */
            coder: string | null;
            /** Model */
            model: string | null;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            /** Outcome */
            outcome: string | null;
            /** Reason */
            reason: string | null;
            /** Peak Context Pct */
            peak_context_pct: number | null;
            /** Context Badge */
            context_badge: boolean;
            /** Files Touched */
            files_touched: number;
            /** Commits */
            commits: string[];
            result: components["schemas"]["TaskResult"] | null;
            /** Has Summary */
            has_summary: boolean;
            /** Has Prompt */
            has_prompt: boolean;
        };
        /**
         * TaskAttemptListResponse
         * @description Envelope for GET /api/tasks/{id}/attempts.
         */
        TaskAttemptListResponse: {
            /** Attempts */
            attempts: components["schemas"]["TaskAttempt"][];
        };
        /**
         * TaskChild
         * @description One child bead of an epic.
         */
        TaskChild: {
            /** Id */
            id: string;
            /** Title */
            title: string | null;
            /** Status */
            status: string | null;
            /** Result Status */
            result_status: string | null;
            /** Result Summary */
            result_summary: string | null;
        };
        /**
         * TaskChildren
         * @description Children panel payload for GET /api/tasks/{id}/children.
         */
        TaskChildren: {
            /** Children */
            children: components["schemas"]["TaskChild"][];
            /** Children Md */
            children_md: string | null;
        };
        /**
         * TaskDetail
         * @description One task with its attempts timeline (GET /api/tasks/{id}).
         */
        TaskDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /** Status */
            status: string;
            /** Cwd */
            cwd: string | null;
            /** Coder */
            coder: string | null;
            /** Model */
            model: string | null;
            /** Priority */
            priority: number | null;
            /** Depends On */
            depends_on: string[];
            /** Created At */
            created_at: string | null;
            /** Started At */
            started_at: string | null;
            /** Ended At */
            ended_at: string | null;
            /** Elapsed Sec */
            elapsed_sec: number | null;
            /** Idle Sec */
            idle_sec: number | null;
            /** Events */
            events: number;
            /** Context Tokens */
            context_tokens: number | null;
            /** Context Pct */
            context_pct: number | null;
            /** Context Limit */
            context_limit: number | null;
            /** Last Event Kind */
            last_event_kind: string | null;
            /** Last Event Detail */
            last_event_detail: string | null;
            /** Blocked Reason */
            blocked_reason: string | null;
            /** Blocked At */
            blocked_at: string | null;
            /** Ignore Until */
            ignore_until: string | null;
            /** Ignored */
            ignored: boolean;
            rounds: components["schemas"]["TaskRounds"];
            /** Restarts */
            restarts: number;
            /** Context Rounds */
            context_rounds: number;
            /** Compactions */
            compactions: number;
            /** Peak Context Pct */
            peak_context_pct: number | null;
            /** Last Outcome */
            last_outcome: string | null;
            /** Last Outcome Reason */
            last_outcome_reason: string | null;
            /** Last Action */
            last_action: string | null;
            result: components["schemas"]["TaskResult"] | null;
            /** State Excerpt */
            state_excerpt: string | null;
            /** Worker */
            worker: string | null;
            /** Job Phase */
            job_phase: string | null;
            job_artifacts: components["schemas"]["JobArtifacts"];
            /** Steps */
            steps: components["schemas"]["RunStep"][];
            lease: components["schemas"]["TaskLease"] | null;
            /** Attempts */
            attempts: components["schemas"]["TaskAttempt"][];
        };
        /**
         * TaskEventsResponse
         * @description Paged envelope for GET /api/tasks/{id}/events.
         */
        TaskEventsResponse: {
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Events */
            events: components["schemas"]["StreamEvent"][];
        };
        /**
         * TaskLease
         * @description Claim lease from the latest attempt's run.json, null when absent.
         */
        TaskLease: {
            /** Heartbeat At */
            heartbeat_at: string;
            /** Lease Until */
            lease_until: string;
            /** Alive */
            alive: boolean;
        };
        /**
         * TaskListResponse
         * @description Envelope for GET /api/tasks.
         */
        TaskListResponse: {
            /** Tasks */
            tasks: components["schemas"]["TaskDetail"][];
        };
        /**
         * TaskResult
         * @description The worker's declared outcome (live RESULT.json or latest snapshot).
         */
        TaskResult: {
            /** Schema */
            schema: number;
            /**
             * Status
             * @enum {string}
             */
            status: "done" | "partial" | "blocked";
            /** Summary */
            summary: string;
            /** Commits */
            commits: string[];
            /** Tests */
            tests: {
                [key: string]: unknown;
            } | null;
            /** Open Questions */
            open_questions: string[];
            /** Next Step */
            next_step: string;
            /** Blocked Reason */
            blocked_reason: string;
            /** Followups */
            followups?: components["schemas"]["FollowupItem"][];
        };
        /**
         * TaskRounds
         * @description Trailing-streak retry rounds, from attempts.jsonl.
         */
        TaskRounds: {
            /** Failure */
            failure: number;
            /** Stall */
            stall: number;
            /** Context */
            context: number;
            /** Partial */
            partial: number;
            /** Noclose */
            noclose: number;
        };
        /**
         * Template
         * @description One prompt template stored under the fleet home.
         */
        Template: {
            /** Name */
            name: string;
            /** Content */
            content: string;
        };
        /**
         * TemplateListResponse
         * @description Envelope for GET /api/templates.
         */
        TemplateListResponse: {
            /** Templates */
            templates: components["schemas"]["Template"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                closed_limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateTaskResponse"];
                };
            };
        };
    };
    coders_api_coders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoderListResponse"];
                };
            };
        };
    };
    list_templates_api_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
        };
    };
    get_task_api_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_task_attempts_api_tasks__task_id__attempts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskAttemptListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_children_api_tasks__task_id__children_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskChildren"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attempt_summary_api_tasks__task_id__attempts__attempt_no__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                attempt_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attempt_state_api_tasks__task_id__attempts__attempt_no__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                attempt_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attempt_prompt_api_tasks__task_id__attempts__attempt_no__prompt_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                attempt_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attempt_log_api_tasks__task_id__attempts__attempt_no__log_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                attempt_no: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kill_task_api_tasks__task_id__kill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    requeue_task_api_tasks__task_id__requeue_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unblock_task_api_tasks__task_id__unblock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unignore_task_api_tasks__task_id__unignore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_task_api_tasks__task_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_assignee_api_tasks__task_id__remove_assignee_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_state_api_tasks__task_id__artifacts_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_result_api_tasks__task_id__artifacts_result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_outputs_api_tasks__task_id__artifacts_outputs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutputsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_research_api_tasks__task_id__artifacts_research_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_design_api_tasks__task_id__artifacts_design_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_diff_api_tasks__task_id__diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_logs_api_tasks__task_id__logs_get: {
        parameters: {
            query?: {
                level?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_stderr_api_tasks__task_id__stderr_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_files_api_tasks__task_id__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_events_api_tasks__task_id__events_get: {
        parameters: {
            query?: {
                offset?: number | null;
                limit?: number;
                kind?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_beads_api_beads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeadListResponse"];
                };
            };
        };
    };
    get_bead_api_beads__bead_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_status_api_beads__bead_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unblock_bead_api_beads__bead_id__unblock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_bead_assignee_api_beads__bead_id__remove_assignee_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bead_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supervisor_status_api_supervisor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupervisorResponse"];
                };
            };
        };
    };
    pause_supervisor_api_supervisor_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PauseResponse"];
                };
            };
        };
    };
    resume_supervisor_api_supervisor_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PauseResponse"];
                };
            };
        };
    };
    restart_supervisor_api_supervisor_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestartResponse"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
        };
    };
    put_config_api_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
        };
    };
    get_summary_api_analytics_summary_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_questions_api_chat_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionListResponse"];
                };
            };
        };
    };
    answer_question_api_chat_questions__qid__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
